import { Link, useRouterState } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, Bell, BookOpen, Bookmark, Check, Compass, HandHeart, Heart, Home, Leaf, MapPin, MessageCircle, Plus, ShieldCheck, Sprout, User, Users, Menu, X } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useArpan } from '@/lib/arpan/state';
import type { Entry } from '@/lib/arpan/data';
export function Mark(){return <span className="brand-mark"><Sprout strokeWidth={1.6}/></span>}
export function Brand(){return <Link to="/" className="brand"><Mark/><span>ARPAN<small>TECHNOLOGY AS SEVA</small></span></Link>}
const nav = [{to:'/home',label:'Home',icon:Home},{to:'/explore',label:'Explore',icon:Compass},{to:'/offer',label:'Offer',icon:HandHeart},{to:'/ask',label:'Ask',icon:Heart},{to:'/seva',label:'Seva',icon:Users},{to:'/institutions',label:'Institutions',icon:Leaf},{to:'/journey',label:'Journey',icon:BookOpen},{to:'/chats',label:'Chats',icon:MessageCircle}] as const;
export function Shell({children}:{children:ReactNode}) {
 const path=useRouterState({select:s=>s.location.pathname}); const publicPage=['/','/about','/philosophy','/how-it-works','/login','/signup'].includes(path); const [menu,setMenu]=useState(false); const {name,read}=useArpan();
 return <div className={publicPage?'public-shell':'app-shell'}><header className="topbar"><Brand/><nav className="public-nav" aria-label="Main navigation">{publicPage?<><Link to="/explore">Explore</Link><Link to="/about">About ARPAN</Link><Link to="/philosophy">Our philosophy</Link><Link to="/how-it-works">How it works</Link></>:<span className="topbar-message">Offer what you can. Be present.</span>}</nav><div className="header-actions">{publicPage?<><Link className="login-link" to="/login">Log in</Link><Button asChild><Link to="/signup">Begin with ARPAN <ArrowUpRight/></Link></Button></>:<><span className="demo-badge">DEMO EXPERIENCE</span><Button variant="ghost" size="icon" asChild title="Notifications"><Link aria-label="Notifications" to="/notifications"><Bell/>{read.length===0&&<span className="notification-dot"/>}</Link></Button><Link className="avatar" to="/profile" aria-label="Your profile">{name.slice(0,1)}</Link></>}<Button className="menu-button" size="icon" variant="ghost" aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></header>{menu&&<nav className="mobile-menu" aria-label="Expanded navigation" onClick={()=>setMenu(false)}>{publicPage?<><Link to="/explore">Explore</Link><Link to="/about">About ARPAN</Link><Link to="/philosophy">Our philosophy</Link><Link to="/how-it-works">How it works</Link></>:nav.map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</nav>}{!publicPage&&<aside className="sidebar"><nav aria-label="Community navigation">{nav.map(n=><Link key={n.to} to={n.to} className={path===n.to||path.startsWith(n.to+'/')?'side-link active':'side-link'}><n.icon/>{n.label}</Link>)}</nav><div className="sidebar-bottom"><ShieldCheck/><p>A place to give.<br/>A place to receive.<br/>A place to belong.</p><Link to="/about">The spirit of ARPAN <ArrowUpRight size={14}/></Link><Link className="admin-link" to="/admin">Demo moderation</Link></div></aside>}<main className={publicPage?'public-main':'app-main'}>{children}</main>{!publicPage&&<nav className="bottom-nav" aria-label="Mobile navigation">{nav.filter(n=>['Home','Explore','Journey'].includes(n.label)).map(n=><Link key={n.to} to={n.to} className={path.startsWith(n.to)?'active':''}><n.icon/>{n.label}</Link>)}<Link to="/profile"><User/>Profile</Link></nav>}{publicPage&&<Footer/>}</div>
}
export function Footer(){return <footer className="footer"><div className="container footer-inner"><Brand/><p>Offer yourself. Grow by serving.</p><div><Link to="/philosophy">Our philosophy</Link><Link to="/about">About</Link><Link to="/explore">Explore</Link></div><small>© 2026 ARPAN · Built around dignity.</small></div></footer>}
export function PageHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function DemoNote(){return <p className="demo-note"><ShieldCheck size={14}/> A demo community. All opportunities, requests and institutions are fictional; verification is simulated.</p>}
export function EntryLink({entry,children,className}:{entry:Entry;children:ReactNode;className?:string}){if(entry.kind==='seva')return <Link className={className} to="/seva/$id" params={{id:entry.id}}>{children}</Link>;if(entry.kind==='institutions')return <Link className={className} to="/institutions/$id" params={{id:entry.id}}>{children}</Link>;if(entry.kind==='offers')return <Link className={className} to="/offer/$id" params={{id:entry.id}}>{children}</Link>;return <Link className={className} to="/needs/$id" params={{id:entry.id}}>{children}</Link>}
export function EntryCard({entry}:{entry:Entry}) { const {saved,toggleSave}=useArpan();return <article className={`entry-card ${entry.image?'':'text-card'}`}>{entry.image&&<EntryLink entry={entry} className="card-image"><img src={entry.image} alt={entry.title} loading="lazy" width={1024} height={768}/><span className="image-category">{entry.category}</span></EntryLink>}<div className="card-content"><div className="card-meta"><span className="demo-badge">DEMO</span>{entry.verified&&<span className="verified"><ShieldCheck size={13}/> Demo reviewed</span>}<Button size="icon" variant="ghost" className="bookmark-button" title={saved.includes(entry.id)?'Remove saved opportunity':'Save opportunity'} aria-label={saved.includes(entry.id)?'Remove saved opportunity':'Save opportunity'} onClick={()=>toggleSave(entry.id)}><Bookmark className={saved.includes(entry.id)?'saved':''}/></Button></div>{!entry.image&&<span className="text-category">{entry.category}</span>}<EntryLink entry={entry}><h3>{entry.title}</h3></EntryLink><p>{entry.context}</p><div className="card-location"><MapPin size={14}/>{entry.location}<span>·</span>{entry.kind==='seva'?'Sat, 10 Oct':entry.kind==='offers'?'Weekends':'Community-visible'}</div><div className="card-footer"><span>{entry.kind==='seva'?`${entry.time} · ${entry.duration}`:entry.kind==='institutions'?'Time, skills & resources':'Offer what you can'}</span><EntryLink entry={entry}>{entry.kind==='offers'?'Connect':entry.kind==='needs'?'View need':entry.kind==='institutions'?'Meet the community':'Explore Seva'}<ArrowUpRight size={16}/></EntryLink></div></div></article>}
const actions=[{title:'Offer',text:'Give what you have.',detail:'Your time, skills, or a little of what you can spare.',to:'/offer/create',icon:HandHeart,tone:'offer'},{title:'Ask',text:'Ask when you need.',detail:'A helping hand. A listening ear. A way forward.',to:'/ask/create',icon:Heart,tone:'ask'},{title:'Serve',text:'Show up with others.',detail:'Find a seva that speaks to you. Be a part of it.',to:'/seva',icon:Users,tone:'serve'},{title:'Support',text:'Stand with a community.',detail:'Connect with institutions doing meaningful work.',to:'/institutions',icon:Leaf,tone:'support'}] as const;
export function ActionGrid(){return <div className="action-grid">{actions.map(a=><Link key={a.title} to={a.to} className={`action-item ${a.tone}`}><div className="action-top"><span className="action-icon"><a.icon strokeWidth={1.5}/></span><ArrowUpRight size={18}/></div><span className="eyebrow">{a.title}</span><h3>{a.text}</h3><p>{a.detail}</p></Link>)}</div>}
export function Empty({title='Nothing here right now.',text='Try a different search, or come back when the time feels right.',onReset}:{title?:string;text?:string;onReset?:()=>void}){return <div className="empty-state"><Sprout size={40} strokeWidth={1}/><h3>{title}</h3><p>{text}</p>{onReset&&<Button variant="outline" onClick={onReset}>Clear filters</Button>}</div>}
export function Success({title,text,children}:{title:string;text:string;children?:ReactNode}){return <div className="success-state"><span><Check size={30}/></span><h1>{title}</h1><p>{text}</p>{children}</div>}
export { ArrowRight, ArrowUpRight, Plus };
