/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SevaRouteImport } from './routes/seva'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminInstitutionsRouteImport } from './routes/admin.institutions'
import { Route as AdminNeedsRouteImport } from './routes/admin.needs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSevaRouteImport } from './routes/admin.seva'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AskCreateRouteImport } from './routes/ask.create'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreInstitutionsRouteImport } from './routes/explore.institutions'
import { Route as ExploreNeedsRouteImport } from './routes/explore.needs'
import { Route as ExploreOffersRouteImport } from './routes/explore.offers'
import { Route as ExploreSevaRouteImport } from './routes/explore.seva'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as InstitutionsIdRouteImport } from './routes/institutions.$id'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as NeedsIdRouteImport } from './routes/needs.$id'
import { Route as OfferIndexRouteImport } from './routes/offer.index'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as OfferCreateRouteImport } from './routes/offer.create'
import { Route as SevaIndexRouteImport } from './routes/seva.index'
import { Route as SevaIdRouteImport } from './routes/seva.$id'
import { Route as SevaCreateRouteImport } from './routes/seva.create'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as JourneyReflectionIdRouteImport } from './routes/journey.reflection.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SevaRoute = SevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitutionsRoute = AdminInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNeedsRoute = AdminNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSevaRoute = AdminSevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AskRoute,
} as any)
const AskCreateRoute = AskCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AskRoute,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreInstitutionsRoute = ExploreInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreNeedsRoute = ExploreNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreOffersRoute = ExploreOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreSevaRoute = ExploreSevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => ExploreRoute,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionsRoute,
} as any)
const InstitutionsIdRoute = InstitutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InstitutionsRoute,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyRoute,
} as any)
const NeedsIdRoute = NeedsIdRouteImport.update({
  id: '/needs/$id',
  path: '/needs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIndexRoute = OfferIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfferRoute,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfferRoute,
} as any)
const OfferCreateRoute = OfferCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OfferRoute,
} as any)
const SevaIndexRoute = SevaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SevaRoute,
} as any)
const SevaIdRoute = SevaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SevaRoute,
} as any)
const SevaCreateRoute = SevaCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SevaRoute,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyReflectionIdRoute = JourneyReflectionIdRouteImport.update({
  id: '/reflection/$id',
  path: '/reflection/$id',
  getParentRoute: () => JourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRouteWithChildren
  '/chats': typeof ChatsRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/institutions': typeof InstitutionsRouteWithChildren
  '/journey': typeof JourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offer': typeof OfferRouteWithChildren
  '/philosophy': typeof PhilosophyRoute
  '/profile': typeof ProfileRoute
  '/seva': typeof SevaRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seva': typeof AdminSevaRoute
  '/admin/users': typeof AdminUsersRoute
  '/ask/create': typeof AskCreateRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/institutions': typeof ExploreInstitutionsRoute
  '/explore/needs': typeof ExploreNeedsRoute
  '/explore/offers': typeof ExploreOffersRoute
  '/explore/seva': typeof ExploreSevaRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/offer/create': typeof OfferCreateRoute
  '/seva/$id': typeof SevaIdRoute
  '/seva/create': typeof SevaCreateRoute
  '/support/$id': typeof SupportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ask/': typeof AskIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/journey/': typeof JourneyIndexRoute
  '/offer/': typeof OfferIndexRoute
  '/seva/': typeof SevaIndexRoute
  '/journey/reflection/$id': typeof JourneyReflectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/philosophy': typeof PhilosophyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seva': typeof AdminSevaRoute
  '/admin/users': typeof AdminUsersRoute
  '/ask/create': typeof AskCreateRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/institutions': typeof ExploreInstitutionsRoute
  '/explore/needs': typeof ExploreNeedsRoute
  '/explore/offers': typeof ExploreOffersRoute
  '/explore/seva': typeof ExploreSevaRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/offer/create': typeof OfferCreateRoute
  '/seva/$id': typeof SevaIdRoute
  '/seva/create': typeof SevaCreateRoute
  '/support/$id': typeof SupportIdRoute
  '/admin': typeof AdminIndexRoute
  '/ask': typeof AskIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/journey': typeof JourneyIndexRoute
  '/offer': typeof OfferIndexRoute
  '/seva': typeof SevaIndexRoute
  '/journey/reflection/$id': typeof JourneyReflectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRouteWithChildren
  '/chats': typeof ChatsRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/institutions': typeof InstitutionsRouteWithChildren
  '/journey': typeof JourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offer': typeof OfferRouteWithChildren
  '/philosophy': typeof PhilosophyRoute
  '/profile': typeof ProfileRoute
  '/seva': typeof SevaRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seva': typeof AdminSevaRoute
  '/admin/users': typeof AdminUsersRoute
  '/ask/create': typeof AskCreateRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/institutions': typeof ExploreInstitutionsRoute
  '/explore/needs': typeof ExploreNeedsRoute
  '/explore/offers': typeof ExploreOffersRoute
  '/explore/seva': typeof ExploreSevaRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/offer/create': typeof OfferCreateRoute
  '/seva/$id': typeof SevaIdRoute
  '/seva/create': typeof SevaCreateRoute
  '/support/$id': typeof SupportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ask/': typeof AskIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/journey/': typeof JourneyIndexRoute
  '/offer/': typeof OfferIndexRoute
  '/seva/': typeof SevaIndexRoute
  '/journey/reflection/$id': typeof JourneyReflectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/chats'
    | '/explore'
    | '/home'
    | '/how-it-works'
    | '/institutions'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/offer'
    | '/philosophy'
    | '/profile'
    | '/seva'
    | '/signup'
    | '/admin/content'
    | '/admin/institutions'
    | '/admin/needs'
    | '/admin/reports'
    | '/admin/seva'
    | '/admin/users'
    | '/ask/create'
    | '/chats/$id'
    | '/explore/institutions'
    | '/explore/needs'
    | '/explore/offers'
    | '/explore/seva'
    | '/institutions/$id'
    | '/needs/$id'
    | '/offer/$id'
    | '/offer/create'
    | '/seva/$id'
    | '/seva/create'
    | '/support/$id'
    | '/admin/'
    | '/ask/'
    | '/chats/'
    | '/explore/'
    | '/institutions/'
    | '/journey/'
    | '/offer/'
    | '/seva/'
    | '/journey/reflection/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/philosophy'
    | '/profile'
    | '/signup'
    | '/admin/content'
    | '/admin/institutions'
    | '/admin/needs'
    | '/admin/reports'
    | '/admin/seva'
    | '/admin/users'
    | '/ask/create'
    | '/chats/$id'
    | '/explore/institutions'
    | '/explore/needs'
    | '/explore/offers'
    | '/explore/seva'
    | '/institutions/$id'
    | '/needs/$id'
    | '/offer/$id'
    | '/offer/create'
    | '/seva/$id'
    | '/seva/create'
    | '/support/$id'
    | '/admin'
    | '/ask'
    | '/chats'
    | '/explore'
    | '/institutions'
    | '/journey'
    | '/offer'
    | '/seva'
    | '/journey/reflection/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/chats'
    | '/explore'
    | '/home'
    | '/how-it-works'
    | '/institutions'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/offer'
    | '/philosophy'
    | '/profile'
    | '/seva'
    | '/signup'
    | '/admin/content'
    | '/admin/institutions'
    | '/admin/needs'
    | '/admin/reports'
    | '/admin/seva'
    | '/admin/users'
    | '/ask/create'
    | '/chats/$id'
    | '/explore/institutions'
    | '/explore/needs'
    | '/explore/offers'
    | '/explore/seva'
    | '/institutions/$id'
    | '/needs/$id'
    | '/offer/$id'
    | '/offer/create'
    | '/seva/$id'
    | '/seva/create'
    | '/support/$id'
    | '/admin/'
    | '/ask/'
    | '/chats/'
    | '/explore/'
    | '/institutions/'
    | '/journey/'
    | '/offer/'
    | '/seva/'
    | '/journey/reflection/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRouteWithChildren
  ChatsRoute: typeof ChatsRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InstitutionsRoute: typeof InstitutionsRouteWithChildren
  JourneyRoute: typeof JourneyRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OfferRoute: typeof OfferRouteWithChildren
  PhilosophyRoute: typeof PhilosophyRoute
  ProfileRoute: typeof ProfileRoute
  SevaRoute: typeof SevaRouteWithChildren
  SignupRoute: typeof SignupRoute
  NeedsIdRoute: typeof NeedsIdRoute
  SupportIdRoute: typeof SupportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seva': {
      id: '/seva'
      path: '/seva'
      fullPath: '/seva'
      preLoaderRoute: typeof SevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions': {
      id: '/admin/institutions'
      path: '/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AdminInstitutionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/needs': {
      id: '/admin/needs'
      path: '/needs'
      fullPath: '/admin/needs'
      preLoaderRoute: typeof AdminNeedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seva': {
      id: '/admin/seva'
      path: '/seva'
      fullPath: '/admin/seva'
      preLoaderRoute: typeof AdminSevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ask/': {
      id: '/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof AskRoute
    }
    '/ask/create': {
      id: '/ask/create'
      path: '/create'
      fullPath: '/ask/create'
      preLoaderRoute: typeof AskCreateRouteImport
      parentRoute: typeof AskRoute
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/institutions': {
      id: '/explore/institutions'
      path: '/institutions'
      fullPath: '/explore/institutions'
      preLoaderRoute: typeof ExploreInstitutionsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/needs': {
      id: '/explore/needs'
      path: '/needs'
      fullPath: '/explore/needs'
      preLoaderRoute: typeof ExploreNeedsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/offers': {
      id: '/explore/offers'
      path: '/offers'
      fullPath: '/explore/offers'
      preLoaderRoute: typeof ExploreOffersRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/seva': {
      id: '/explore/seva'
      path: '/seva'
      fullPath: '/explore/seva'
      preLoaderRoute: typeof ExploreSevaRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/institutions/$id': {
      id: '/institutions/$id'
      path: '/$id'
      fullPath: '/institutions/$id'
      preLoaderRoute: typeof InstitutionsIdRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/journey/': {
      id: '/journey/'
      path: '/'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/needs/$id': {
      id: '/needs/$id'
      path: '/needs/$id'
      fullPath: '/needs/$id'
      preLoaderRoute: typeof NeedsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/': {
      id: '/offer/'
      path: '/'
      fullPath: '/offer/'
      preLoaderRoute: typeof OfferIndexRouteImport
      parentRoute: typeof OfferRoute
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof OfferRoute
    }
    '/offer/create': {
      id: '/offer/create'
      path: '/create'
      fullPath: '/offer/create'
      preLoaderRoute: typeof OfferCreateRouteImport
      parentRoute: typeof OfferRoute
    }
    '/seva/': {
      id: '/seva/'
      path: '/'
      fullPath: '/seva/'
      preLoaderRoute: typeof SevaIndexRouteImport
      parentRoute: typeof SevaRoute
    }
    '/seva/$id': {
      id: '/seva/$id'
      path: '/$id'
      fullPath: '/seva/$id'
      preLoaderRoute: typeof SevaIdRouteImport
      parentRoute: typeof SevaRoute
    }
    '/seva/create': {
      id: '/seva/create'
      path: '/create'
      fullPath: '/seva/create'
      preLoaderRoute: typeof SevaCreateRouteImport
      parentRoute: typeof SevaRoute
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/reflection/$id': {
      id: '/journey/reflection/$id'
      path: '/reflection/$id'
      fullPath: '/journey/reflection/$id'
      preLoaderRoute: typeof JourneyReflectionIdRouteImport
      parentRoute: typeof JourneyRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminInstitutionsRoute: typeof AdminInstitutionsRoute
  AdminNeedsRoute: typeof AdminNeedsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSevaRoute: typeof AdminSevaRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminInstitutionsRoute: AdminInstitutionsRoute,
  AdminNeedsRoute: AdminNeedsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSevaRoute: AdminSevaRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AskRouteChildren {
  AskCreateRoute: typeof AskCreateRoute
  AskIndexRoute: typeof AskIndexRoute
}

const AskRouteChildren: AskRouteChildren = {
  AskCreateRoute: AskCreateRoute,
  AskIndexRoute: AskIndexRoute,
}

const AskRouteWithChildren = AskRoute._addFileChildren(AskRouteChildren)

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface ExploreRouteChildren {
  ExploreInstitutionsRoute: typeof ExploreInstitutionsRoute
  ExploreNeedsRoute: typeof ExploreNeedsRoute
  ExploreOffersRoute: typeof ExploreOffersRoute
  ExploreSevaRoute: typeof ExploreSevaRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreInstitutionsRoute: ExploreInstitutionsRoute,
  ExploreNeedsRoute: ExploreNeedsRoute,
  ExploreOffersRoute: ExploreOffersRoute,
  ExploreSevaRoute: ExploreSevaRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface InstitutionsRouteChildren {
  InstitutionsIdRoute: typeof InstitutionsIdRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
}

const InstitutionsRouteChildren: InstitutionsRouteChildren = {
  InstitutionsIdRoute: InstitutionsIdRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
}

const InstitutionsRouteWithChildren = InstitutionsRoute._addFileChildren(
  InstitutionsRouteChildren,
)

interface JourneyRouteChildren {
  JourneyIndexRoute: typeof JourneyIndexRoute
  JourneyReflectionIdRoute: typeof JourneyReflectionIdRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyIndexRoute: JourneyIndexRoute,
  JourneyReflectionIdRoute: JourneyReflectionIdRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

interface OfferRouteChildren {
  OfferIdRoute: typeof OfferIdRoute
  OfferCreateRoute: typeof OfferCreateRoute
  OfferIndexRoute: typeof OfferIndexRoute
}

const OfferRouteChildren: OfferRouteChildren = {
  OfferIdRoute: OfferIdRoute,
  OfferCreateRoute: OfferCreateRoute,
  OfferIndexRoute: OfferIndexRoute,
}

const OfferRouteWithChildren = OfferRoute._addFileChildren(OfferRouteChildren)

interface SevaRouteChildren {
  SevaIdRoute: typeof SevaIdRoute
  SevaCreateRoute: typeof SevaCreateRoute
  SevaIndexRoute: typeof SevaIndexRoute
}

const SevaRouteChildren: SevaRouteChildren = {
  SevaIdRoute: SevaIdRoute,
  SevaCreateRoute: SevaCreateRoute,
  SevaIndexRoute: SevaIndexRoute,
}

const SevaRouteWithChildren = SevaRoute._addFileChildren(SevaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRouteWithChildren,
  ChatsRoute: ChatsRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  InstitutionsRoute: InstitutionsRouteWithChildren,
  JourneyRoute: JourneyRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OfferRoute: OfferRouteWithChildren,
  PhilosophyRoute: PhilosophyRoute,
  ProfileRoute: ProfileRoute,
  SevaRoute: SevaRouteWithChildren,
  SignupRoute: SignupRoute,
  NeedsIdRoute: NeedsIdRoute,
  SupportIdRoute: SupportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
